#! /usr/bin/env node

if (process.argv.length > 2)
  return require('scuttlebot/bin')

var config = require('scuttlebot/config')

var sbot = require('scuttlebot').init(config)
  .use(require('ssbplug-phoenix'))

// write server manifest
var fs = require('fs')
var path = require('path')

var manifestFile = path.join(config.path, 'manifest.json')
fs.writeFileSync(
  manifestFile,
  JSON.stringify(sbot.getManifest(), null, 2)
)

